# Generated by Django 2.2.7 on 2020-03-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ordinal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=32)),
                ('geometry_file', models.FileField(upload_to='geometry/')),
                ('source_file', models.FileField(upload_to='sources/')),
                ('content_file', models.FileField(upload_to='content/')),
                ('equation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.EquationType')),
            ],
        ),
    ]
