# Generated by Django 2.2.7 on 2020-03-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200323_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('geometry_file', models.FileField(upload_to='geometry/')),
            ],
        ),
        migrations.RemoveField(
            model_name='equation',
            name='geometry_file',
        ),
        migrations.RemoveField(
            model_name='equation',
            name='number',
        ),
        migrations.AddField(
            model_name='equation',
            name='geometry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Geometry'),
            preserve_default=False,
        ),
    ]
