# Generated by Django 2.2.7 on 2020-03-30 02:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0007_auto_20200327_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExactUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='equation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ExactUser'),
        ),
        migrations.AlterField(
            model_name='equationtype',
            name='coordinate_system',
            field=models.CharField(choices=[('Cartesian', 'Cartesian'), ('Cylindrical', 'Cylindrical'), ('Spherical', 'Spherical'), ('Other', 'Other')], default='Cartesian', max_length=32),
        ),
    ]
