# Generated by Django 2.2.7 on 2020-04-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200330_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationtype',
            name='coordinate_system',
            field=models.CharField(default='Cartesian', max_length=32),
        ),
    ]
