# Generated by Django 2.2.7 on 2020-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200404_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='geometry_file',
            field=models.FileField(blank=True, upload_to='geometry/'),
        ),
        migrations.AddIndex(
            model_name='equationtype',
            index=models.Index(fields=['coordinate_system'], name='api_equatio_coordin_caab6b_idx'),
        ),
        migrations.AddIndex(
            model_name='geometry',
            index=models.Index(fields=['number'], name='api_geometr_number_bf73f3_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['name'], name='api_page_name_63aad5_idx'),
        ),
    ]
