# Generated by Django 2.2.7 on 2020-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200404_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
