# Generated by Django 2.2.7 on 2020-04-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200408_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equationtype',
            name='ordinal',
        ),
    ]
