# Generated by Django 2.2.7 on 2020-04-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_equationtype_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='content_file',
            field=models.FileField(blank=True, upload_to='content/'),
        ),
    ]
