# Generated by Django 2.2.7 on 2020-04-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_froalaimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='froalaimage',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
