# Generated by Django 2.2.7 on 2020-04-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200415_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='froalaimage',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
