# Generated by Django 3.0.5 on 2020-12-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200415_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='equationtype',
            name='coordinate_system',
            field=models.CharField(max_length=64),
        ),
    ]
